// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fluhdkcadquavjknrgoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsdWhka2NhZHF1YXZqa25yZ29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTk3NzksImV4cCI6MjA2NDY5NTc3OX0.7b80cFWfbueiZFCwBe0zcBxXNgqAyn_7eCKqL4IczbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);